### PR TITLE
Selection the last card match

### PR DESCRIPTION
**Pull request by fernandoperigolo**
When i type 5 in card number, its match Master Card, Maestro and ELO brands. before this changes, only Master Card are selected. Now the last match only is select. I dont know if it solve all card brands selection problems, but now it works well with Master Card, Maestro and ELO.

### CODE REVIEW

**Comment by rikterbeek** [comment]
Hi Luiz,

With the first character it matches multiple card bins. I don't understand what the benefit is of showing the last match instead of the first match. Could you explain?

Regards,
Rik
Adyen

**Comment by fernandoperigolo** [comment]
The benefit is ELO can be selected and it dont broke Master Card and Maestro.
ELO and Maestro will always be match, because 50 contains in both. So if i type a number starting with, 506699, it return Maestro insted ELO. So i solve the problem returning the last match, and now ELO is correctly select.

Until now: type 5 it select Master Card > type 0 it select Maestro > try to type an ELO, ELO never selected.

After my changes: type 5 select ELO > Type 0 select ELO > try to type an ELO, ELO select.
But it dont broke Master Card and Maestro selection.

I'm preatty sure have a best solution to this situation, maybe use regex, so one rule do not overwrite other. But for now, it is the way i find to be possible to sell using all cards.

I hope you understand.

**Comment by rikterbeek** [comment]
Hi Fernando,

In your case this will work indeed but it is not the best implementation. The best fix for this problem is that the card number will match the most specific card rule that exits. We will make this change in the upcoming weeks we keep you updated when we have this fix implemented.

Regards,
Rik
Adyen

**Comment by fernandoperigolo** [comment]
Perfect, Rik. Keep this workaround in mind if other client needs to sell with MC, MS and ELO, it can helps until you create a final solution.

**Comment by rikterbeek** [comment]
Thanks for sharing this problem with us we will keep you updated.

**Pull request closed without merging**
