### PR TITLE
Translation to portuguese

### PR DESCRIPTION
**Pull request by raphaelpor**
Hi!

This PR add a new file with the translation to pt-br. :wink:

### CODE REVIEW

**Comment by rikterbeek** [comment]
Hi Raphael,

Thanks for the pull request. I will let some portugees speaker look at this. When it is aproved i will add it into the module.

Regards,
Rik
Adyen

**Comment by raphaelpor** [comment]
Thanks Rik!

:)

Em seg, 7 de set de 2015 07:38, Rik ter Beek <notifications@github.com>
escreveu:

> Hi Raphael,
>
> Thanks for the pull request. I will let some portugees speaker look at
> this. When it is aproved i will add it into the module.
>
> Regards,
> Rik
> Adyen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Adyen/magento/pull/400#issuecomment-138267050>.
>
-- 
Raphael Porto.

**Comment by rikterbeek** [comment]
Hi Raphael,

I am going to merge your pull request to our module but i am going to make these changes to it:
6 - +"Authorize Only","Somente Autorizar”
17 - +"The payment is REFUSED by Adyen.", “O Pagamento foi RECUSADO pela Adyen."
19 +"Your payment failed, Please try again later",”Sua tentativa de pagamento falhou. Por favor, tente novamente.”
44 +"The payment is PENDING by Adyen.","O pagamento está PENDENTE pela Adyen.”
45 +"The payment is AUTHORIZED by Adyen.","O pagamento foi AUTORIZADO pela Adyen.”
48 +"You will be redirected to Adyen website when you place an order.”,”Você será redirecionado ao site da Ayen quando realizar a compra.”
54 +"Remember these details”,"Armazenar estes dados"

Regards,
Rik
Adyen

**Comment by raphaelpor** [comment]
:+1:

**Pull request merged**
