### PR TITLE
Obscure PCI sensitive data in logs

### PR DESCRIPTION
**Pull request by hughgrigg**
Currently PCI sensitive data (credit card details) are logged to disk.
This commit obscures PCI sensitive data before it is written to log
files.

### CODE REVIEW

**Comment by rikterbeek** [comment]
Hi hughgrigg,

Thanks for the pull request. For your understanding this is only the case when you are using our full API instead of CSE(Client Side Encryption) If you turn this on it will never be logged.

I can imagine if you are on the full API you do not want this to be logged. Most of the time the log is then just disabled on the live environment so this issue will not occur. I think we can add this code, I  am going to check if we not need a setting where you can still enable this for debugging purposes. 

I see that you have implement ArrayAccess for the Adyen_Payment_Model_Adyen_Data_Abstract model can you tell me why you have done this ?

Regards,
Rik ter Beek
Adyen

**Comment by hughgrigg** [comment]
Hi Rik

Thanks for the explanation, wasn't aware of that.

I've implemented ArrayAccess for Adyen_Payment_Model_Adyen_Data_Abstract to
allow the obscuring code to easily work through all the keys of the objects
it is passed and obscure sensitive ones.

Hugh


2015-03-27 7:03 GMT+00:00 Rik ter Beek <notifications@github.com>:

**Comment by rikterbeek** [comment]
Hi Hugh,

Thanks for the explanation. I merged the code into the repository.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Hugh,

some extra Brackets where missing I add those see https://github.com/Adyen/magento/commit/bfa3ad7a4a5c2b74d920d1003bb594fbf4718ebe

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Hugh,

Error is occurred with a customer in this part of the code:
Parse error: syntax error, unexpected '[' in /var/www/x5690/app/code/community/Adyen/Payment/Model/Adyen/Data/Abstract.php on line 63

Could you solve this ?

Regards,
Rik
Adyen

**Comment by hughgrigg** [comment]
Hi Rik

Sorry for the late reply, I have been away travelling.

Presumably that would be this file?
https://github.com/hughgrigg/magento/blob/develop-2.3.0/app/code/community/Adyen/Payment/Model/Adyen/Data/Abstract.php

If it is, there is no line 63.

Could you show me the line in question?

Thanks

Hugh

2015-04-28 11:39 GMT+01:00 Rik ter Beek <notifications@github.com>:

**Comment by rikterbeek** [comment]
Hi Hugh,

It is something you have implement in your PCI sensitive data logging. See our repository:
https://github.com/Adyen/magento/blob/develop-2.3.0/app/code/community/Adyen/Payment/Model/Adyen/Data/Abstract.php
or your own:
https://github.com/hughgrigg/magento/blob/pci-sensitive-data-logging/app/code/community/Adyen/Payment/Model/Adyen/Data/Abstract.php

Regards,
Rik
Adyen

**Comment by hughgrigg** [comment]
Hi Rik

Sorry I was looking at the wrong branch.

I see the issue at
https://github.com/hughgrigg/magento/blob/pci-sensitive-data-logging/app/code/community/Adyen/Payment/Model/Adyen/Data/Abstract.php#L63
now.

I believe the error the client is seeing is due to them not using PHP 5.4
or above. Considering 5.4 was released in 2013 it would be advisable for
them to upgrade.

However I have changed that method to not use the newer array access
syntax, which should fix the issue. The PR is
https://github.com/Adyen/magento/pull/287

Thanks

Hugh


2015-05-11 8:01 GMT+01:00 Rik ter Beek <notifications@github.com>:

**Pull request merged**
