### PR TITLE
Bugfix: Strip special characters from id in ideal form template

### PR DESCRIPTION
**Pull request by edkoster**
Slashes in the $_issueId caused 'unrecognized expression' errors in IE11

### CODE REVIEW

**Comment by rikterbeek** [comment]
Hi Edwin,

Could you explain why you are doing this? because issuerId should be a simple code with numbers and does not contain any special characters.

Regards,
Rik
Adyen

**Comment by edkoster** [comment]
That's strange. 
As far as i can see in `Adyen_Payment_Model_Adyen_Ideal::getIssuers()`  on line 50 the key of the returned array is filled with `$issuer['issuerId'].'/'.$issuer['name']` which is containing a slash.

See: https://github.com/Adyen/magento/blob/develop/app/code/community/Adyen/Payment/Model/Adyen/Ideal.php#L50

**Comment by rikterbeek** [comment]
Hi Edwin,

I have made a better fix see commit above. 

Regards,
Rik
Adyen

**Comment by edkoster** [comment]
Your fix is nicer indeed. I've added a comment to it since i think there's a typo in it.

When do you plan to release a new version containing this fix?

**Comment by rikterbeek** [comment]
Hi Edwin,

The spelling mistake is fixed. I will do a hotfix release 2.5.3 tomorrow included only this fix.

Regards,
Rik

**Comment by edkoster** [comment]
Thanks a lot!

**Pull request closed without merging**
