### PR TITLE
Improved the error `MerchantAccount in notification is not the same as in Magento settings`.

### PR DESCRIPTION
**Pull request by weerdenburg**
You now see what the encoding type of the Merchant Account settings are and if it contains a leading or trailing space.

For some reason it already happened multiple times that a leading or trailing space was copied into the Magento config field.
It took a lot of time to figure this out, because it `looks` like the correct settings are set.

This results in log info like:

- In case of leading or trailing space:
`... DEBUG (7): Merchant Account in notification (UTF-8, 10 chars) is not the same as in Magento settings (UTF-8, 11 chars, contains a leading or trailing space!)`

- In case of a mismatch:
`... DEBUG (7): Merchant Account in notification (UTF-8, 10 chars) is not the same as in Magento settings (UTF-8, 15 chars)`

### CODE REVIEW

**Comment by rikterbeek** [comment]
Hi Mike,

Thanks for the pull request. Is it not better to just trim() these config parameters then it does not matter if you have leading or trailing spaces.

Regards,
Rik
Adyen

**Comment by weerdenburg** [comment]
Hi Rik,

I understand the suggested solution (just trim the values), but I do not like the fact that the config in Magento would still contain the space. If for some reason somebody uses the same config field in another flow (like some custom code, a refunding cron for example), than the mismatch error will still occur in that code.

A better solution would then be to use a special back-end-model for the config field, that trim's extra spaces of the value during the config save. But for me... that is out of scope for now ;-)


In both cases that I encountered this problem with a leading space, I stared with adjusting the debug info, so it just outputs the 2 values. But even then, we did not see the space ;-)

So that's why I thought it would be nice to add a little check for that.

For security reasons, I do not output the real values, but ASCII/UTF8, length.

**Comment by rikterbeek** [comment]
Hi Mike,

That sound like a better fix. I just added some trim before saving for the merchantAccount field. see:
https://github.com/Adyen/magento/commit/7cff957d7843848a875113ca3dff154914207485

Regards,
Rik
Adyen

**Comment by weerdenburg** [comment]
Nice, thanks!

**Pull request closed without merging**
