### PR TITLE
+: first status cancel then succes issue with ideal.

### PR DESCRIPTION
**Pull request by basselalaraaj**
First we get the message that the order payment where canceled, thats when we cancel the order.
Then we get the message that the order payment is succesful, then it tries to proccess the order.
Causing the order to come in a state, not able to do anything anymore with the order.

### CODE REVIEW

**Comment by basselalaraaj** [comment]
Made this for kega, martijn.

**Comment by rikterbeek** [comment]
Hi Bassel,

Why do you get a message that the payment is cancelled when the resultUrl result is authorised ?

Regards,
Rik
Adyen

**Comment by basselalaraaj** [comment]
@martijn-kega

**Comment by martijn-kega** [comment]
Hi Rik,

This is the solution for the problem i addressed 25-2-2016 17.16 via e-mail. You responded "De notificatie geeft aan of de betaling is gelukt om een beveiligde manier. Wat je zou kunnen toevoegen in je script is als de adyen status “AUTHORISED” is niet gelijk te cancellen maar dit pas na bijv een dag te doen.". 

If you need more information, maybe its good to have a brief call.

Regards,
Martijn vd Hulst

**Comment by rikterbeek** [comment]
Hi Martijn,

Yes that is what I said but this means you need to modify your cancellation script and not our module.
Setting a separate status on resultUrl is a lot of overhead what is just not needed.

Regards,
Rik
Adyen

**Comment by basselalaraaj** [comment]
@rikterbeek how can we recognize pending ideal orders that are authorized. Since AUTHORISED is only a comment and not a order field.

**Comment by rikterbeek** [comment]
Hi Bassel,

That's true. What a better solution is then to do this for all authorised payments:

$order->setAdyenEventCode($authResult);
$order->save();

Can you modify this into your PR ?

Regards,
Rik

**Comment by basselalaraaj** [comment]
@rikterbeek this will work for us, this would be great!

**Comment by rikterbeek** [comment]
Hi Bassel,

Thanks for the changes in the PR. I will merge it now.

Regards,
Rik
Adyen

**Pull request merged**
