### PR TITLE
[develop] +: making uncancelorder logic configurable.

### PR DESCRIPTION
**Pull request by basselalaraaj**
This new functionalty breaks current logic in our webshops.
So there for we want to have this configurable.

### CODE REVIEW

**Comment by rikterbeek** [comment]
Hi Bassel,

Thanks for the pull request. Yes I can imagine you don't want this by default because of stock issues that can occur. I will merge this pull request into the develop branch and will be in the next release.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Bassel,

I changed the position of the setting and added a tooltip.
https://github.com/Adyen/magento/commit/00f2c1735a7cdbfe1064b105c37b6f82f49645f5

Regards,
Rik
Adyen

**Comment by basselalaraaj** [comment]
@rikterbeek good, thnq! do you know when the next release will be?

**Comment by basselalaraaj** [comment]
@rikterbeek do you know when the next release will be?

**Comment by rikterbeek** [comment]
Hi Bassel,

It is now in beta see: https://github.com/Adyen/magento/tree/release-2.5.0
Works fine in latest versions of magento need to be tested to older version.

Regards,
Rik

**Comment by basselalaraaj** [comment]
@rikterbeek great, i was curious about the timeline, when the 2.5.0 will be an official release?

**Pull request merged**
