### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by paales**
- Input validation doesn't work properly when the element has no value
- Only load adyen billing agreements
- Ability to get the billing agreement from the method instance
- Input validation doesn't work properly when the element has no value
- Support for default billing agreements

### CODE REVIEW

**Comment by rikterbeek** [comment]
Hi Paul,

Thanks for the pull request it looks good so i will merge this pull request.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Updated the language files as well with the new generic error message see: da720d234c371af8a6ab7b55389483e10476dc41

**Comment by paales** [comment]
@rikterbeek That was the commit from @guangmian, that wasn't committed to the develop branch.

**Comment by rikterbeek** [comment]
@paales yes I see. Never mind it is fixed.

**Pull request merged**
